// Generated by CoffeeScript 1.6.3
App.util = {
  randomDate: function(start, end) {
    if (start == null) {
      start = new Date(new Date() - 12096e5);
    }
    if (end == null) {
      end = new Date();
    }
    return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
  },
  randomArrayItem: function(arr) {
    return arr[Math.floor(Math.random() * arr.length)];
  },
  prefetchImage: function(src) {
    var img;
    img = new Image();
    return img.src = src;
  },
  mixinArrayMethods: function() {
    var methods;
    methods = ['each', 'map', 'reduce', 'reduceRight', 'detect', 'select', 'reject', 'all', 'any', 'include', 'invoke', 'pluck', 'max', 'min', 'sortBy', 'sortedIndex', 'toArray', 'size', 'first', 'rest', 'last', 'without', 'indexOf', 'lastIndexOf', 'isEmpty', 'unique'];
    return _.each(methods, function(method) {
      return Array.prototype[method] = function() {
        return _[method].apply(_, [this].concat(_.toArray(arguments)));
      };
    });
  },
  isEmpty: function($el) {
    return !$.trim($el.html);
  }
};
